namespace NodeJS {
    interface ProcessEnv {
        FIREBASE_API_KEY: string
        FIREBASE_PROJECT_ID: string
        FIREBASE_ADMIN_CLIENT_EMAIL: string
        FIREBASE_ADMIN_PRIVATE_KEY: string

        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string
        NEXT_PUBLIC_NIGHT_MAP_ID: string
        NEXT_PUBLIC_DEFAULT_MAP_ID: string
        NEXT_PUBLIC_FIREBASE_API_KEY: string
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: string
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string
        NEXT_PUBLIC_FIREBASE_APP_ID: string
        NEXT_PUBLIC_FIREBASE_KEY_PAIR: string
    }
}