import "@/styles/globals.css";
import "quill/dist/quill.core.css";
import type { Metadata } from "next";
import Providers from "./providers";
import { poppins } from "@/config";
import clsx from "clsx";
export const metadata: Metadata = {
  title: "Lightness | Admin",
  description: "Generated by Lemsa Innovation",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={clsx(poppins.className, "bg-background antialiased")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
